Repository tigerblue77/Dell_iDRAC_fan_controller_Docker, pull requests merged in 2023-02, with the labels that each got.

#33 Added disable and enable_third_party_profiles
  Dell_iDRAC_fan_controller.sh
  Dockerfile
  README.md
Labels: enhancement, good first issue

#35 Added option to disable third-party PCIe card default cooling response
  Dell_iDRAC_fan_controller.sh
  Dockerfile
  README.md
Labels: enhancement

#31 Added comments for clarity
  Dell_iDRAC_fan_controller.sh
Labels: documentation
